FROM <IMAGE>
ENV ARCH <ARCH>

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      ca-certificates \
      tini \
      git \
      libressl \
    && adduser -Du 1000 caddy

RUN echo "hello world" > /home/caddy/index.html

VOLUME ["/etc/caddy"]
VOLUME ["/home/caddy"]

COPY caddy /usr/sbin/caddy

# Run as an unprivileged user.
USER caddy
ENTRYPOINT ["/sbin/tini", "--", "/usr/sbin/caddy"]
